services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  dirsrv:
    extends:
      file: deps.yaml
      service: dirsrv

  keycloak:
    hostname: keycloak
    container_name: keycloak
    depends_on:
      oracle:
        condition: service_healthy
      dirsrv:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8080'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      TZ: 'America/New_York'
      KC_DB: oracle
      KC_DB_URL: jdbc:oracle:thin:@//oracle:1521/xepdb1
      KC_DB_USERNAME: keycloak_owner
      KC_DB_PASSWORD: password
    volumes:
      - ./container/keycloak/initdb.d:/container-entrypoint-initdb.d
