services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  dirsrv:
    extends:
      file: deps.yaml
      service: dirsrv

  keycloak:
    hostname: keycloak
    container_name: keycloak
    depends_on:
      oracle:
        condition: service_healthy
      dirsrv:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "9990:9990"
    environment:
      KC_FRONTEND_URL: 'http://localhost:8081/auth'
      KC_BACKEND_URL: 'http://keycloak:8080/auth'
      KC_HTTP_RELATIVE_PATH: '/auth'
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
      KC_DB: oracle
      KC_DB_URL: jdbc:oracle:thin:@//oracle:1521/xepdb1
      KC_DB_USERNAME: keycloak_owner
      KC_DB_PASSWORD: password
      TZ: 'America/New_York'
    volumes:
      - ./container/keycloak/initdb.d:/container-entrypoint-initdb.d
