services:
  keycloak:
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8080'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      TZ: 'America/New_York'
    volumes:
      - ./scripts/example/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
